apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-csi-hostpath-sc-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc

